### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MingdongHe** [kymikim0401/ESPCN_Pytorch#1]
Maybe there is a bug in the dataset.py  file, in line 15 and line 48
 it is 

> reduced_dim = (int(truth_image.shape[0]/self.upscale), int(truth_image.shape[1]/self.upscale))

should be 

> reduced_dim = (int(truth_image.shape[1]/self.upscale), int(truth_image.shape[0]/self.upscale))

**Comment by kymikim0401** [comment]
thnks for pointing out the mistake!
